version: '2'
services:
  app:
    build:
      context : .
      dockerfile: Dockerfile-rails
    command: rails s -b 0.0.0.0 -p 3000
    tty: true
    volumes:
      - .:/app
    ports:
      - 3000:3000
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./docker/nginx/sslfiles:/etc/nginx/sslfiles
    links:
      - app
    ports:
      - "80:80"
      - "443:443"
